export enum Permissao {
    ADMIN = 'ROLE_ADMIN',  
    USER = 'ROLE_USER',
    GERENTE_DE_TI = 'ROLE_GERENTE_DE_TI',
    COORDENADOR_DE_TI = 'ROLE_COORDENADOR_DE_TI',
    RH = 'ROLE_RH',
    PROFESSOR = 'ROLE_PROFESSOR',
    DESENVOLVEDOR = 'ROLE_DESENVOLVEDOR',
    ESTAGIARIO = 'ROLE_ESTAGIARIO',
    TRAINEE = 'ROLE_TRAINEE'
}
